keep-starknet-strange/blobstream-starknet

src/tree/namespace/merkle_tree.cairo

feat: build out tree

---

.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/gh-pages.yml
book/src/SUMMARY.md
book/src/overview/README.md

dev: doc update, ci

---

.github/workflows/gh-pages.yml

dev: doc buildout

---

.github/workflows/gh-pages.yml
book/book.toml

35 dev doc buildout

---

book/book.toml

update book icons for back linking to repo

dev: book icons

---

book/book.toml

dev: update for cname

---

src/lib.cairo
src/tests/test_blobstream.cairo

Contract errors and implementation of the function using it

feat: Blobstream errors

---

CONTRIBUTING.md
src/lib.cairo

dev: update TODO fmt

---

.all-contributorsrc
CONTRIBUTING.md
README.md
book/src/overview/README.md
src/lib.cairo

dev: fix all contribs

---

.all-contributorsrc
.github/workflows/check.yml
CONTRIBUTING.md
README.md

dev: add Jordy

---

src/interfaces.cairo
src/lib.cairo
src/mocks/upgraded.cairo
src/tests/test_blobstream.cairo

Added Openzeppelins ownable and upgradeability components. Upgradeability was added as a new interface to increase reusability. Tests implemented

feat: Upgradeability and access control

---

.all-contributorsrc

contribs: fix all contribs

---

src/lib.cairo

Added DataRootTupleRootEvent and ValidatorSetUpdatedEvent

Add events and their emissions

---

.all-contributorsrc
CONTRIBUTING.md
README.md

:busts_in_silhouette: Add @OthmanSefraoui as a contributor

contrib: :busts_in_silhouette: Add @OthmanSefraoui as a contributor

---

.all-contributorsrc
CONTRIBUTING.md
README.md

:busts_in_silhouette: Add @b-j-roberts as a contributor

---

src/interfaces.cairo
src/lib.cairo
src/tests/common.cairo
src/tests/test_blobstreamx.cairo

BlobstreamX functions implementation in cairo

Blobstream X Funcs 

---

.all-contributorsrc
CONTRIBUTING.md
README.md

:busts_in_silhouette: Add @ametel01 as a contributor

---

src/interfaces.cairo
src/lib.cairo
src/tests/test_blobstreamx.cairo

Add request_header_range and HeaderRangeRequested

---

.all-contributorsrc
CONTRIBUTING.md
README.md

:busts_in_silhouette: Add @faytey as a contributor

---

.all-contributorsrc
CONTRIBUTING.md
README.md
blobby/src/app/components/HeroText.tsx

Add @remybar as a contributor to the project.

contrib: remybar

---

src/blobstreamx.cairo
src/interfaces.cairo
src/succinctx/tests/test_fee_vault.cairo
src/tests/common.cairo
src/tests/test_blobstreamx.cairo
src/tests/test_ownable.cairo
src/tests/test_upgradeable.cairo

Implemented the frozen functionality and refactored some imports following good practices discussed in piltover.

feat: allow freezing blobstreamx

---

.all-contributorsrc
CONTRIBUTING.md
README.md
src/succinctx/tests/test_fee_vault.cairo

Contrib: Add thomas192 as a contributor

---

scripts/deploy-blobstreamx.sh

Addresses: https://github.com/keep-starknet-strange/blobstream-starknet/pull/135#discussion_r1552377521

Making Sepolia deployment script less path dependent

---

scripts/verify-da.sh

feat: da verification script
